server:
  port: 8081

spring:
  application:
    name: account-service
  datasource:
    url: jdbc:postgresql://localhost:5433/account_db
    username: user_devsu
    password: password_devsu
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest